In [1]:
from ERKER2Phenopackets.src.utils.io import read_files, phenopacket2dict

from pathlib import Path

In [2]:
path = Path(r'C:\Users\Surface\OneDrive\Documents\DataSpell\ERKER2Phenopackets\ERKER2Phenopackets\data\out\phenopackets\example-phenopackets-from-synthetic-data')

In [3]:
phenopackets = read_files(path)

In [4]:
from ERKER2Phenopackets.src.analysis.tree_comparison.edit_dist import compare_structure

In [5]:
import numpy as np

A = np.zeros((len(phenopackets), len(phenopackets)))
block = 'interpretations'#'phenotypicFeatures'
for i, p in enumerate(phenopackets):
    for j, q in enumerate(phenopackets):
        try:
            comparison = compare_structure(phenopacket2dict(p)[block], phenopacket2dict(q)[block])
        except KeyError:
            print(p.id, q.id, False)
            A[i, j] = 0
            continue
        else:
            print(p.id, q.id, comparison[0])
            A[i, j] = comparison[0]
            

0 0 True
0 1 True
0 10 False
0 11 False
0 12 True
0 13 True
0 14 False
0 15 False
0 16 False
0 17 True
0 18 True
0 19 False
0 2 True
0 20 True
0 21 True
0 22 True
0 23 True
0 24 True
0 25 True
0 26 True
0 27 False
0 28 False
0 29 True
0 3 True
0 30 False
0 31 True
0 32 True
0 33 True
0 34 False
0 35 False
0 36 True
0 37 True
0 38 True
0 39 True
0 4 True
0 40 False
0 41 True
0 42 True
0 43 True
0 44 True
0 45 True
0 46 True
0 47 True
0 48 True
0 49 False
0 5 False
0 6 False
0 7 True
0 8 False
0 9 True
1 0 True
1 1 True
1 10 False
1 11 False
1 12 True
1 13 True
1 14 False
1 15 False
1 16 False
1 17 True
1 18 True
1 19 False
1 2 True
1 20 True
1 21 True
1 22 True
1 23 True
1 24 True
1 25 True
1 26 True
1 27 False
1 28 False
1 29 True
1 3 True
1 30 False
1 31 True
1 32 True
1 33 True
1 34 False
1 35 False
1 36 True
1 37 True
1 38 True
1 39 True
1 4 True
1 40 False
1 41 True
1 42 True
1 43 True
1 44 True
1 45 True
1 46 True
1 47 True
1 48 True
1 49 False
1 5 False
1 6 False
1 7 True
1 8 Fal

In [6]:
print(A)

[[1. 1. 0. ... 1. 0. 1.]
 [1. 1. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [1. 1. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 1. 0.]
 [1. 1. 0. ... 1. 0. 1.]]


In [7]:
print(f'N: {len(phenopackets) ** 2}')
print(f'Matches: {np.count_nonzero(A) - len(phenopackets)}')
print(f'No matches: {np.count_nonzero(A == 0) + len(phenopackets)}')

N: 2500
Matches: 1306
No matches: 1194


In [6]:
from ERKER2Phenopackets.src.analysis.tree_comparison.edit_dist import edit_distance

d1 = {'a': {'b': {'c': 2}, 'd': {'e': 3}}}
d2 = {'a': {'b': {'c': 2}}}
edit_distance(d1, d2, subtree_substitution_cost=1, insertion_cost=1, val_substitution_cost=1)

0